# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/BRAM_mem_gen_12x307200/BRAM_mem_gen_12x307200.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BRAM_mem_gen_12x307200 || ORIG_REF_NAME==BRAM_mem_gen_12x307200} -quiet] -quiet
