# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/PracticeWorks/UART_cpu_VGA_controller/UART_cpu_VGA_controller.srcs/sources_1/ip/BRAM_mem_gen_12x307200/BRAM_mem_gen_12x307200.xci
# IP: The module: 'BRAM_mem_gen_12x307200' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/PracticeWorks/UART_cpu_VGA_controller/UART_cpu_VGA_controller.gen/sources_1/ip/BRAM_mem_gen_12x307200/BRAM_mem_gen_12x307200_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_mem_gen_12x307200'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/PracticeWorks/UART_cpu_VGA_controller/UART_cpu_VGA_controller.srcs/sources_1/ip/BRAM_mem_gen_12x307200/BRAM_mem_gen_12x307200.xci
# IP: The module: 'BRAM_mem_gen_12x307200' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/PracticeWorks/UART_cpu_VGA_controller/UART_cpu_VGA_controller.gen/sources_1/ip/BRAM_mem_gen_12x307200/BRAM_mem_gen_12x307200_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_mem_gen_12x307200'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
